name: Deploy to Vercel

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Desplegar a Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}